import { CoverData, PresetUniversity, ThemeDefinition } from './types';

export const THEMES: ThemeDefinition[] = [
  {
    id: 'fcub-ribbon',
    name: 'FCUB Signature Ribbon',
    nameBn: 'এফসিইউবি অরিজিনাল ফিতা থিম',
    description: 'The exact signature green-red corner swoops with diamond divider and classic framing as in your demo.',
    defaultPrimary: '#005A36',
    defaultAccent: '#E31B23',
    previewBg: 'bg-emerald-900',
    badge: 'Original Demo',
  },
  {
    id: 'royal-crest',
    name: 'Royal Ivy Crest',
    nameBn: 'রয়্যাল আইভি ও গোল্ডেন ক্রিস্ট',
    description: 'Timeless classical academia with ornate corner brackets, double gilded border, and formal serif styling.',
    defaultPrimary: '#0F2A4A',
    defaultAccent: '#C5A059',
    previewBg: 'bg-slate-900',
    badge: 'Classical',
  },
  {
    id: 'modern-minimal',
    name: 'Modern Minimalist',
    nameBn: 'মডার্ন মিনিমালিস্ট এ্যালিমেন্ট',
    description: 'Clean architectural line-work with geometric accents, uncluttered whitespace, and crisp modern typography.',
    defaultPrimary: '#1E293B',
    defaultAccent: '#2563EB',
    previewBg: 'bg-blue-950',
    badge: 'Minimal',
  },
  {
    id: 'tech-engineer',
    name: 'Tech & Engineering',
    nameBn: 'টেক ও ইঞ্জিনিয়ারিং (CSE/EEE)',
    description: 'Hexagonal corner nodes, technical coordinates, deep navy and cyan framing for lab reports & projects.',
    defaultPrimary: '#0B192C',
    defaultAccent: '#00A896',
    previewBg: 'bg-cyan-950',
    badge: 'Engineering',
  },
  {
    id: 'national-emerald',
    name: 'National Emerald & Crimson',
    nameBn: 'বাংলাদেশ এমারেল্ড ও লাল',
    description: 'Prestigious national emerald green and crimson ribbon styling, popular across public universities.',
    defaultPrimary: '#006A4E',
    defaultAccent: '#F42A41',
    previewBg: 'bg-green-950',
    badge: 'Heritage',
  },
  {
    id: 'executive-report',
    name: 'Executive Business Report',
    nameBn: 'এক্সিকিউটিভ বিজনেস (BBA/MBA)',
    description: 'Polished corporate header band with structured table layout, ideal for case studies & term papers.',
    defaultPrimary: '#18181B',
    defaultAccent: '#D97706',
    previewBg: 'bg-amber-950',
    badge: 'Corporate',
  },
  {
    id: 'creative-portfolio',
    name: 'Presentation & Group Project',
    nameBn: 'প্রেজেন্টেশন ও গ্রুপ প্রজেক্ট',
    description: 'Bold asymmetric headline block with multi-student team cards, designed for slide decks and presentations.',
    defaultPrimary: '#3B0764',
    defaultAccent: '#7C3AED',
    previewBg: 'bg-purple-950',
    badge: 'Team / Deck',
  },
  {
    id: 'medical-science',
    name: 'Medical & Life Sciences',
    nameBn: 'মেডিকেল ও লাইফ সায়েন্স',
    description: 'Refined deep teal clinical framing with subtle caduceus watermark lines for MBBS, Pharmacy & Bio.',
    defaultPrimary: '#0F766E',
    defaultAccent: '#0284C7',
    previewBg: 'bg-teal-950',
    badge: 'Clinical',
  },
];

export const FONT_OPTIONS = [
  { id: 'Merriweather', name: 'Merriweather (Academic Serif)', class: 'font-merriweather' },
  { id: 'Playfair Display', name: 'Playfair Display (Luxury Serif)', class: 'font-playfair' },
  { id: 'Cormorant Garamond', name: 'Cormorant Garamond (Ivy Classic)', class: 'font-cormorant' },
  { id: 'Cinzel', name: 'Cinzel (Formal Engraved)', class: 'font-cinzel' },
  { id: 'Plus Jakarta Sans', name: 'Plus Jakarta Sans (Modern Sans)', class: 'font-jakarta' },
  { id: 'Montserrat', name: 'Montserrat (Bold Clean)', class: 'font-montserrat' },
  { id: 'Poppins', name: 'Poppins (Geometric Modern)', class: 'font-poppins' },
  { id: 'Lora', name: 'Lora (Editorial Prose)', class: 'font-lora' },
];

export const PRESET_UNIVERSITIES: PresetUniversity[] = [
  {
    id: 'fcub',
    name: 'First Capital University of Bangladesh (FCUB)',
    department: 'Department of English',
    courseCode: 'ENG:205',
    subjectName: 'THE GARDEN PARTY',
    logoUrl: '/fcub-logo.png',
    primaryColor: '#005A36',
    accentColor: '#E31B23',
    themeId: 'fcub-ribbon',
    assignmentType: 'Assignment',
  },
  {
    id: 'du',
    name: 'University of Dhaka',
    department: 'Department of Computer Science & Engineering',
    courseCode: 'CSE-3101',
    subjectName: 'DISTRIBUTED SYSTEMS & CLOUD ARCHITECTURE',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/87/University_of_Dhaka_logo.svg/300px-University_of_Dhaka_logo.svg.png',
    primaryColor: '#00478F',
    accentColor: '#B30000',
    themeId: 'royal-crest',
    assignmentType: 'Assignment',
  },
  {
    id: 'buet',
    name: 'Bangladesh University of Engineering and Technology (BUET)',
    department: 'Department of Electrical & Electronic Engineering',
    courseCode: 'EEE 405',
    subjectName: 'ADVANCED EMBEDDED SYSTEMS & ROBOTICS',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/BUET_LOGO.svg/300px-BUET_LOGO.svg.png',
    primaryColor: '#800000',
    accentColor: '#0F172A',
    themeId: 'tech-engineer',
    assignmentType: 'Lab Report',
  },
  {
    id: 'bracu',
    name: 'BRAC University',
    department: 'BRAC Business School (BBS)',
    courseCode: 'ACT 201',
    subjectName: 'FINANCIAL ACCOUNTING & CORPORATE VALUATION',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/90/BRAC_University_logo.svg/300px-BRAC_University_logo.svg.png',
    primaryColor: '#00509D',
    accentColor: '#FFB703',
    themeId: 'executive-report',
    assignmentType: 'Term Paper',
  },
  {
    id: 'nsu',
    name: 'North South University (NSU)',
    department: 'Department of Economics',
    courseCode: 'ECO 101',
    subjectName: 'PRINCIPLES OF MICROECONOMIC THEORY',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/North_South_University_Monogram.svg/300px-North_South_University_Monogram.svg.png',
    primaryColor: '#0A2540',
    accentColor: '#10B981',
    themeId: 'modern-minimal',
    assignmentType: 'Presentation',
  },
];

export const INITIAL_COVER_DATA: CoverData = {
  universityName: 'First Capital University of Bangladesh (FCUB)',
  departmentName: 'Department of English',
  facultyName: 'Faculty of Arts and Social Sciences',
  assignmentType: 'Assignment',
  courseCode: 'ENG:205',
  subjectName: 'THE GARDEN PARTY',
  topicSubtitle: 'A Critical Analysis of Social Class & Modernism',
  themeId: 'fcub-ribbon',
  fontFamily: 'Merriweather',
  
  logoUrl: '/fcub-logo.png',
  logoScale: 110,
  logoShape: 'original',
  logoPosition: 'center',
  showLogo: true,

  primaryColor: '#005A36',
  accentColor: '#E31B23',
  textColor: '#111827',
  paperBgColor: '#FFFFFF',
  borderWidth: 2,
  hasCornerRibbons: true,
  showWatermark: false,
  watermarkOpacity: 0.05,

  submissionMode: 'underline',
  isGroupSubmission: false,
  submittedBy: [
    {
      id: '1',
      name: 'MD. Abdullah Al Mamun',
      studentId: '221-02-0542',
      department: 'Department of English',
      program: 'B.A. (Hons.) in English',
      semester: '6th Semester',
      batch: '21st Batch',
      section: 'A',
      roll: '05',
    },
  ],
  submittedTo: {
    name: 'Dr. Shahinur Rahman',
    designation: 'Assistant Professor & Head',
    department: 'Department of English',
    faculty: 'First Capital University of Bangladesh',
  },
  submissionDate: new Date().toISOString().split('T')[0],
  session: '2023-2024',
  academicYear: '2024',
};
